"""update knowledge question study tables

Revision ID: 78c3f2d533a7
Revises: e6f7a8b9c0d1
Create Date: 2026-06-17 23:24:31.993962

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78c3f2d533a7'
down_revision: str | Sequence[str] | None = 'e6f7a8b9c0d1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_points', 'summary',
               existing_type=sa.VARCHAR(length=500),
               comment='知识点简短说明。',
               existing_comment='知识点简短说明。MVP 不保存大段资料正文。',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'created_by_user_id',
               existing_type=sa.BIGINT(),
               comment='用户补充内容的创建者 ID，官方可为空。',
               existing_comment='用户补充内容的创建者 ID，官方或 AI 内容可为空。',
               existing_nullable=True)
    op.drop_column('knowledge_points', 'source_type')
    op.alter_column('question_answers', 'content',
               existing_type=sa.TEXT(),
               comment='答案内容。',
               existing_comment='答案内容，可为面试口述版、详细版或用户补充版。',
               existing_nullable=False)
    op.alter_column('question_answers', 'source_type',
               existing_type=sa.VARCHAR(length=30),
               comment='答案来源：official、user_supplement。官方答案同一题只允许一个。',
               existing_comment='答案来源：ai、official、user_supplement。',
               existing_nullable=False,
               existing_server_default=sa.text("'official'::character varying"))
    op.drop_index(op.f('ix_question_answers_question_status_sort'), table_name='question_answers')
    op.drop_index(op.f('uq_question_answers_preferred_active'), table_name='question_answers', postgresql_where="((is_preferred = true) AND ((status)::text = 'active'::text))")
    op.create_index('ix_question_answers_question_status_source', 'question_answers', ['question_id', 'status', 'source_type', sa.literal_column('created_at DESC'), 'id'], unique=False)
    op.create_index('uq_question_answers_official', 'question_answers', ['question_id'], unique=True, postgresql_where=sa.text("source_type = 'official'"))
    op.drop_column('question_answers', 'sort_order')
    op.drop_column('question_answers', 'source_note')
    op.drop_column('question_answers', 'is_preferred')
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=30),
               comment='题目类型：开放面试题、单选、多选、判断。',
               existing_comment='题目类型：开放面试题、单选、多选、判断、短答、coding。',
               existing_nullable=False,
               existing_server_default=sa.text("'interview_open'::character varying"))
    op.alter_column('questions', 'source_type',
               existing_type=sa.VARCHAR(length=30),
               comment='题目来源：official、user_supplement。',
               existing_comment='题目来源：ai、official、user_supplement。',
               existing_nullable=False,
               existing_server_default=sa.text("'official'::character varying"))
    op.alter_column('questions', 'review_status',
               existing_type=sa.VARCHAR(length=20),
               comment='审核状态。用户补充内容后续可先进入 draft。',
               existing_comment='审核状态。AI 或用户补充内容后续可先进入 draft。',
               existing_nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('questions', 'created_by_user_id',
               existing_type=sa.BIGINT(),
               comment='用户补充题目的创建者 ID。官方题目可为空。',
               existing_comment='用户补充题目的创建者 ID。官方或 AI 题目可为空。',
               existing_nullable=True)
    op.create_table_comment(
        'questions',
        '公共题目表，支持面试开放题、选择题（单选和多选）、判断题。',
        existing_comment='公共题目表，支持面试开放题、选择题、判断题和后续 coding 题。',
        schema=None
    )
    op.drop_column('study_task_progress', 'partial_count')
    op.alter_column('study_task_question_attempts', 'answer_text',
               existing_type=sa.TEXT(),
               comment='简答题的本次作答内容。',
               existing_comment='开放题、短答题或 coding 题的本次作答内容。',
               existing_nullable=True)
    op.drop_column('study_task_question_attempts', 'feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_task_question_attempts', sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True, comment='本次作答反馈。MVP 可为空，后续可由 AI 生成。'))
    op.alter_column('study_task_question_attempts', 'answer_text',
               existing_type=sa.TEXT(),
               comment='开放题、短答题或 coding 题的本次作答内容。',
               existing_comment='简答题的本次作答内容。',
               existing_nullable=True)
    op.add_column('study_task_progress', sa.Column('partial_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False, comment='累计部分正确次数。'))
    op.create_table_comment(
        'questions',
        '公共题目表，支持面试开放题、选择题、判断题和后续 coding 题。',
        existing_comment='公共题目表，支持面试开放题、选择题（单选和多选）、判断题。',
        schema=None
    )
    op.alter_column('questions', 'created_by_user_id',
               existing_type=sa.BIGINT(),
               comment='用户补充题目的创建者 ID。官方或 AI 题目可为空。',
               existing_comment='用户补充题目的创建者 ID。官方题目可为空。',
               existing_nullable=True)
    op.alter_column('questions', 'review_status',
               existing_type=sa.VARCHAR(length=20),
               comment='审核状态。AI 或用户补充内容后续可先进入 draft。',
               existing_comment='审核状态。用户补充内容后续可先进入 draft。',
               existing_nullable=False,
               existing_server_default=sa.text("'approved'::character varying"))
    op.alter_column('questions', 'source_type',
               existing_type=sa.VARCHAR(length=30),
               comment='题目来源：ai、official、user_supplement。',
               existing_comment='题目来源：official、user_supplement。',
               existing_nullable=False,
               existing_server_default=sa.text("'official'::character varying"))
    op.alter_column('questions', 'question_type',
               existing_type=sa.VARCHAR(length=30),
               comment='题目类型：开放面试题、单选、多选、判断、短答、coding。',
               existing_comment='题目类型：开放面试题、单选、多选、判断。',
               existing_nullable=False,
               existing_server_default=sa.text("'interview_open'::character varying"))
    op.add_column('question_answers', sa.Column('is_preferred', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='是否为该题当前推荐展示答案。active 状态下同一题最多一个。'))
    op.add_column('question_answers', sa.Column('source_note', sa.VARCHAR(length=300), autoincrement=False, nullable=True, comment='答案来源补充说明。'))
    op.add_column('question_answers', sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('99'), autoincrement=False, nullable=False, comment='答案展示顺序。'))
    op.drop_index('uq_question_answers_official', table_name='question_answers', postgresql_where=sa.text("source_type = 'official'"))
    op.drop_index('ix_question_answers_question_status_source', table_name='question_answers')
    op.create_index(op.f('uq_question_answers_preferred_active'), 'question_answers', ['question_id'], unique=True, postgresql_where="((is_preferred = true) AND ((status)::text = 'active'::text))")
    op.create_index(op.f('ix_question_answers_question_status_sort'), 'question_answers', ['question_id', 'status', 'sort_order', 'id'], unique=False)
    op.alter_column('question_answers', 'source_type',
               existing_type=sa.VARCHAR(length=30),
               comment='答案来源：ai、official、user_supplement。',
               existing_comment='答案来源：official、user_supplement。官方答案同一题只允许一个。',
               existing_nullable=False,
               existing_server_default=sa.text("'official'::character varying"))
    op.alter_column('question_answers', 'content',
               existing_type=sa.TEXT(),
               comment='答案内容，可为面试口述版、详细版或用户补充版。',
               existing_comment='答案内容。',
               existing_nullable=False)
    op.add_column('knowledge_points', sa.Column('source_type', sa.VARCHAR(length=30), server_default=sa.text("'official'::character varying"), autoincrement=False, nullable=False, comment='内容来源：ai、official、user_supplement。'))
    op.alter_column('knowledge_points', 'created_by_user_id',
               existing_type=sa.BIGINT(),
               comment='用户补充内容的创建者 ID，官方或 AI 内容可为空。',
               existing_comment='用户补充内容的创建者 ID，官方可为空。',
               existing_nullable=True)
    op.alter_column('knowledge_points', 'summary',
               existing_type=sa.VARCHAR(length=500),
               comment='知识点简短说明。MVP 不保存大段资料正文。',
               existing_comment='知识点简短说明。',
               existing_nullable=True)
    # ### end Alembic commands ###
