"""update job table indexs

Revision ID: 8ea16b985736
Revises: d4c9b7e6a2f1
Create Date: 2026-06-07 16:43:04.120611

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ea16b985736"
down_revision: str | Sequence[str] | None = "d4c9b7e6a2f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_auth_identities_provider_email"), table_name="auth_identities")
    op.drop_index(op.f("ix_auth_identities_provider_phone"), table_name="auth_identities")
    op.drop_index(op.f("ix_auth_identities_user_id"), table_name="auth_identities")
    op.drop_index(op.f("ix_auth_identities_user_provider"), table_name="auth_identities")
    op.create_unique_constraint(
        "uq_auth_identities_user_provider", "auth_identities", ["user_id", "provider"]
    )
    op.drop_index(op.f("ix_job_posts_is_remote"), table_name="job_posts")
    op.drop_index(op.f("ix_job_posts_status_created_at"), table_name="job_posts")
    op.drop_index(op.f("ix_job_posts_status_published_at"), table_name="job_posts")
    op.create_index(
        "ix_job_posts_open_created_at",
        "job_posts",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_job_posts_open_published_at",
        "job_posts",
        ["published_at"],
        unique=False,
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.create_table_comment(
        "job_sources",
        "岗位来源表，同一平台可按不同 base_url 拆分具体来源。",
        existing_comment="岗位来源表，例如 alibaba、tencent、jaabz、sample。",
        schema=None,
    )
    op.drop_index(op.f("ix_raw_job_records_raw_content_hash"), table_name="raw_job_records")
    op.drop_index(op.f("ix_raw_job_records_status"), table_name="raw_job_records")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_raw_job_records_status"), "raw_job_records", ["status"], unique=False)
    op.create_index(
        op.f("ix_raw_job_records_raw_content_hash"),
        "raw_job_records",
        ["raw_content_hash"],
        unique=False,
    )
    op.create_table_comment(
        "job_sources",
        "岗位来源表，例如 alibaba、tencent、jaabz、sample。",
        existing_comment="岗位来源表，同一平台可按不同 base_url 拆分具体来源。",
        schema=None,
    )
    op.drop_index(
        "ix_job_posts_open_published_at",
        table_name="job_posts",
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_job_posts_open_created_at",
        table_name="job_posts",
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_job_posts_status_published_at"),
        "job_posts",
        ["status", "published_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_posts_status_created_at"), "job_posts", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_job_posts_is_remote"), "job_posts", ["is_remote"], unique=False)
    op.drop_constraint("uq_auth_identities_user_provider", "auth_identities", type_="unique")
    op.create_index(
        op.f("ix_auth_identities_user_provider"),
        "auth_identities",
        ["user_id", "provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_identities_user_id"), "auth_identities", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_identities_provider_phone"),
        "auth_identities",
        ["provider_phone"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_identities_provider_email"),
        "auth_identities",
        ["provider_email"],
        unique=False,
    )
    # ### end Alembic commands ###
