# ruff: noqa
"""update job tables

Revision ID: 91efd5b091d8
Revises: 864d9b1d5451
Create Date: 2026-06-14 01:01:54.167406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "91efd5b091d8"
down_revision: Union[str, Sequence[str], None] = "864d9b1d5451"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_collection_folders",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="收藏夹主键 ID。"
        ),
        sa.Column(
            "name",
            sa.String(length=80),
            nullable=False,
            comment="收藏夹名称。同一用户下不允许重名。",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="job_collection_folder_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
            comment="收藏夹状态：active 当前使用，archived 已归档。",
        ),
        sa.Column(
            "sort_order",
            sa.Integer(),
            server_default="99",
            nullable=False,
            comment="用户自定义展示排序。数值越小越靠前，默认 99。",
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="归档时间。当前有效记录为空。",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="所属用户 ID。所有用户私有数据查询都必须带该字段做隔离。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_job_collection_folders_user_name"),
        comment="用户岗位收藏夹表，用于单层组织用户收藏岗位。",
    )
    op.create_index(
        "ix_job_collection_folders_user_active_sort",
        "job_collection_folders",
        ["user_id", "sort_order", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_job_collection_folders_user_id"),
        "job_collection_folders",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_skills",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="用户技能画像主键 ID。",
        ),
        sa.Column(
            "skill_id", sa.Integer(), nullable=False, comment="标准技能 ID，关联 skills.id。"
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "archived",
                name="user_skill_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
            comment="技能画像状态：active 当前有效，archived 用户已归档。",
        ),
        sa.Column(
            "source",
            sa.Enum(
                "self_reported",
                "imported",
                "assessment",
                "inferred",
                name="user_skill_source",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="self_reported",
            nullable=False,
            comment="技能来源：self_reported 用户自填，imported 导入，assessment 测评，inferred 系统推断。",
        ),
        sa.Column(
            "proficiency_level",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="掌握等级，1 入门，2 基础，3 可工作，4 熟练，5 专家。",
        ),
        sa.Column(
            "interest_level",
            sa.Integer(),
            server_default="3",
            nullable=False,
            comment="学习意愿等级，1 最低，5 最高，用于后续学习任务排序。",
        ),
        sa.Column(
            "years_of_experience",
            sa.Numeric(precision=4, scale=1),
            nullable=True,
            comment="该技能相关经验年限，可为空。",
        ),
        sa.Column(
            "last_used_at", sa.Date(), nullable=True, comment="用户最近一次实际使用该技能的日期。"
        ),
        sa.Column(
            "evidence",
            sa.String(length=500),
            nullable=True,
            comment="技能掌握证据，例如项目、证书、工作经历摘要。",
        ),
        sa.Column("note", sa.String(length=500), nullable=True, comment="用户对该技能的补充备注。"),
        sa.Column(
            "assessed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="该技能等级最近一次被用户确认或系统评估的时间。",
        ),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="技能画像归档时间。当前 active 时为空。",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="所属用户 ID。所有用户私有数据查询都必须带该字段做隔离。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'active' AND archived_at IS NULL) OR (status = 'archived' AND archived_at IS NOT NULL)",
            name="ck_user_skills_status_archived_at",
        ),
        sa.CheckConstraint(
            "interest_level BETWEEN 1 AND 5", name="ck_user_skills_interest_level_range"
        ),
        sa.CheckConstraint(
            "proficiency_level BETWEEN 1 AND 5", name="ck_user_skills_proficiency_level_range"
        ),
        sa.CheckConstraint(
            "years_of_experience IS NULL OR years_of_experience >= 0",
            name="ck_user_skills_years_of_experience_non_negative",
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "skill_id", name="uq_user_skills_user_skill"),
        comment="用户技能画像表，记录用户对标准技能的掌握等级和补充信息。",
    )
    op.create_index(
        "ix_user_skills_skill_active",
        "user_skills",
        ["skill_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_user_skills_user_active_level",
        "user_skills",
        ["user_id", "proficiency_level", sa.literal_column("updated_at DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(op.f("ix_user_skills_user_id"), "user_skills", ["user_id"], unique=False)
    op.create_table(
        "job_collections",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="岗位收藏主键 ID。"
        ),
        sa.Column(
            "job_post_id",
            sa.BigInteger(),
            nullable=False,
            comment="被收藏岗位 ID，关联 job_posts.id。岗位主数据不应因用户收藏被级联删除。",
        ),
        sa.Column(
            "folder_id",
            sa.BigInteger(),
            nullable=True,
            comment="收藏所属收藏夹 ID。为空表示默认收藏/未分组。",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "removed",
                name="job_collection_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
            comment="收藏状态：active 表示当前收藏，removed 表示用户已取消收藏。",
        ),
        sa.Column(
            "note", sa.String(length=500), nullable=True, comment="用户对该收藏岗位的简短备注。"
        ),
        sa.Column(
            "collected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="最近一次收藏或恢复收藏的时间。",
        ),
        sa.Column(
            "removed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="最近一次取消收藏的时间。当前 active 时为空。",
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="所属用户 ID。所有用户私有数据查询都必须带该字段做隔离。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'active' AND removed_at IS NULL) OR (status = 'removed' AND removed_at IS NOT NULL)",
            name="ck_job_collections_status_removed_at",
        ),
        sa.ForeignKeyConstraint(["folder_id"], ["job_collection_folders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_post_id"], ["job_posts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "job_post_id", name="uq_job_collections_user_job"),
        comment="用户岗位收藏表，记录用户对岗位的兴趣关系和取消状态。",
    )
    op.create_index(
        "ix_job_collections_job_active",
        "job_collections",
        ["job_post_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_job_collections_user_active_collected_at",
        "job_collections",
        ["user_id", sa.literal_column("collected_at DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_job_collections_user_folder_active_collected_at",
        "job_collections",
        ["user_id", "folder_id", sa.literal_column("collected_at DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_job_collections_user_id"), "job_collections", ["user_id"], unique=False
    )
    op.create_table(
        "job_targets",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="目标岗位主键 ID。"
        ),
        sa.Column(
            "job_post_id",
            sa.BigInteger(),
            nullable=False,
            comment="目标岗位 ID，关联 job_posts.id。岗位主数据不应因用户目标被级联删除。",
        ),
        sa.Column(
            "source_collection_id",
            sa.BigInteger(),
            nullable=True,
            comment="从收藏转为目标时关联的收藏记录 ID，可为空。",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "paused",
                "completed",
                "archived",
                name="job_target_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
            comment="目标状态：active 准备中，paused 暂停，completed 已完成，archived 已归档。",
        ),
        sa.Column(
            "priority",
            sa.Integer(),
            server_default="3",
            nullable=False,
            comment="准备优先级，1 最高，5 最低。",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="是否为当前主目标。一个用户最多只能有一个 active/paused 主目标。",
        ),
        sa.Column(
            "note", sa.String(length=500), nullable=True, comment="用户对目标岗位的准备备注。"
        ),
        sa.Column(
            "target_date", sa.Date(), nullable=True, comment="用户希望完成该目标准备的日期。"
        ),
        sa.Column(
            "targeted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="最近一次设为目标岗位的时间。",
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="目标岗位标记完成的时间。",
        ),
        sa.Column(
            "archived_at", sa.DateTime(timezone=True), nullable=True, comment="目标岗位归档的时间。"
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="所属用户 ID。所有用户私有数据查询都必须带该字段做隔离。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status IN ('active', 'paused') AND completed_at IS NULL AND archived_at IS NULL) OR (status = 'completed' AND completed_at IS NOT NULL AND archived_at IS NULL) OR (status = 'archived' AND archived_at IS NOT NULL)",
            name="ck_job_targets_status_timestamps",
        ),
        sa.CheckConstraint(
            "status IN ('active', 'paused') OR is_primary = false",
            name="ck_job_targets_primary_current_status",
        ),
        sa.CheckConstraint("priority BETWEEN 1 AND 5", name="ck_job_targets_priority_range"),
        sa.ForeignKeyConstraint(["job_post_id"], ["job_posts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(
            ["source_collection_id"], ["job_collections.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_collection_id", name="uq_job_targets_source_collection"),
        sa.UniqueConstraint("user_id", "job_post_id", name="uq_job_targets_user_job"),
        comment="用户目标岗位表，记录用户准备目标、优先级、主目标和目标状态。",
    )
    op.create_index(
        "ix_job_targets_job_status", "job_targets", ["job_post_id", "status"], unique=False
    )
    op.create_index(
        "ix_job_targets_user_active_priority",
        "job_targets",
        ["user_id", "priority", sa.literal_column("targeted_at DESC")],
        unique=False,
        postgresql_where=sa.text("status IN ('active', 'paused')"),
    )
    op.create_index(op.f("ix_job_targets_user_id"), "job_targets", ["user_id"], unique=False)
    op.create_index(
        "uq_job_targets_user_primary_active",
        "job_targets",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("is_primary = true AND status IN ('active', 'paused')"),
    )
    op.drop_index(op.f("ix_job_posts_deleted_at"), table_name="job_posts")
    op.drop_index(
        op.f("ix_job_posts_open_published_at_asc_id"),
        table_name="job_posts",
        postgresql_where="(((status)::text = 'open'::text) AND (deleted_at IS NULL))",
    )
    op.drop_index(op.f("ix_raw_job_records_skill_content_hash"), table_name="raw_job_records")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(
        op.f("ix_raw_job_records_skill_content_hash"),
        "raw_job_records",
        ["skill_content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_job_posts_open_published_at_asc_id"),
        "job_posts",
        ["published_at", "id"],
        unique=False,
        postgresql_where="(((status)::text = 'open'::text) AND (deleted_at IS NULL))",
    )
    op.create_index(op.f("ix_job_posts_deleted_at"), "job_posts", ["deleted_at"], unique=False)
    op.drop_index(
        "uq_job_targets_user_primary_active",
        table_name="job_targets",
        postgresql_where=sa.text("is_primary = true AND status IN ('active', 'paused')"),
    )
    op.drop_index(op.f("ix_job_targets_user_id"), table_name="job_targets")
    op.drop_index(
        "ix_job_targets_user_active_priority",
        table_name="job_targets",
        postgresql_where=sa.text("status IN ('active', 'paused')"),
    )
    op.drop_index("ix_job_targets_job_status", table_name="job_targets")
    op.drop_table("job_targets")
    op.drop_index(op.f("ix_job_collections_user_id"), table_name="job_collections")
    op.drop_index(
        "ix_job_collections_user_folder_active_collected_at",
        table_name="job_collections",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "ix_job_collections_user_active_collected_at",
        table_name="job_collections",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "ix_job_collections_job_active",
        table_name="job_collections",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("job_collections")
    op.drop_index(op.f("ix_user_skills_user_id"), table_name="user_skills")
    op.drop_index(
        "ix_user_skills_user_active_level",
        table_name="user_skills",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "ix_user_skills_skill_active",
        table_name="user_skills",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("user_skills")
    op.drop_index(op.f("ix_job_collection_folders_user_id"), table_name="job_collection_folders")
    op.drop_index(
        "ix_job_collection_folders_user_active_sort",
        table_name="job_collection_folders",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("job_collection_folders")
    # ### end Alembic commands ###
