"""fix knowledge table

Revision ID: 9dccae396c94
Revises: 78c3f2d533a7
Create Date: 2026-06-18 11:17:30.115497

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9dccae396c94"
down_revision: str | Sequence[str] | None = "78c3f2d533a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("knowledge_points_created_by_user_id_fkey"), "knowledge_points", type_="foreignkey"
    )
    op.drop_column("knowledge_points", "source_note")
    op.drop_column("knowledge_points", "created_by_user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_points",
        sa.Column(
            "created_by_user_id",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
            comment="用户补充内容的创建者 ID，官方可为空。",
        ),
    )
    op.add_column(
        "knowledge_points",
        sa.Column(
            "source_note",
            sa.VARCHAR(length=300),
            autoincrement=False,
            nullable=True,
            comment="来源补充说明，不保存外部资料正文。",
        ),
    )
    op.create_foreign_key(
        op.f("knowledge_points_created_by_user_id_fkey"),
        "knowledge_points",
        "users",
        ["created_by_user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
