"""optimize static indexes

Revision ID: bcfbbc9e22dd
Revises: a1b2c3d4e5f6
Create Date: 2026-06-20 00:09:49.908796

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcfbbc9e22dd"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

JOB_COLLECTION_FOLDER_STATUS_CHECK = (
    "(status = 'active' AND archived_at IS NULL) "
    "OR (status = 'archived' AND archived_at IS NOT NULL)"
)
QUESTIONS_ACTIVE_APPROVED_LEGACY_WHERE = (
    "(((status)::text = 'active'::text) AND ((review_status)::text = 'approved'::text))"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_job_collection_folders_status_archived_at",
        "job_collection_folders",
        JOB_COLLECTION_FOLDER_STATUS_CHECK,
    )
    op.drop_index(
        op.f("ix_job_collection_folders_user_active_sort"),
        table_name="job_collection_folders",
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.create_index(
        "ix_job_collection_folders_user_active_sort",
        "job_collection_folders",
        [
            "user_id",
            "sort_order",
            sa.literal_column("created_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        op.f("ix_job_collections_user_active_collected_at"),
        table_name="job_collections",
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.create_index(
        "ix_job_collections_user_active_collected_at",
        "job_collections",
        ["user_id", sa.literal_column("collected_at DESC"), sa.literal_column("id DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        op.f("ix_job_collections_user_folder_active_collected_at"),
        table_name="job_collections",
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.create_index(
        "ix_job_collections_user_folder_active_collected_at",
        "job_collections",
        [
            "user_id",
            "folder_id",
            sa.literal_column("collected_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        op.f("ix_knowledge_points_skill_parent_sort"),
        table_name="knowledge_points",
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.create_index(
        "ix_knowledge_points_active_tree_order",
        "knowledge_points",
        ["skill_id", "depth", "parent_id", "sort_order", "id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_question_answers_question_status_source"), table_name="question_answers")
    op.create_index(
        "ix_question_answers_question_active_source_created",
        "question_answers",
        [
            "question_id",
            "source_type",
            sa.literal_column("created_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_question_options_question_correct"), table_name="question_options")
    op.drop_index(
        op.f("ix_questions_active_type_difficulty_id"),
        table_name="questions",
        postgresql_where=QUESTIONS_ACTIVE_APPROVED_LEGACY_WHERE,
    )
    op.drop_index(op.f("ix_questions_source_review_status"), table_name="questions")
    op.create_index(
        "ix_questions_active_created_at_id",
        "questions",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'active' AND review_status = 'approved'"),
    )
    op.create_index(
        "ix_questions_active_type_difficulty_created",
        "questions",
        [
            "question_type",
            "difficulty",
            sa.literal_column("created_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
        postgresql_where=sa.text("status = 'active' AND review_status = 'approved'"),
    )
    op.drop_index(
        op.f("ix_raw_job_records_source_external_job"),
        table_name="raw_job_records",
        postgresql_where="(external_job_id IS NOT NULL)",
    )
    op.drop_index(
        op.f("ix_raw_job_records_source_url"),
        table_name="raw_job_records",
        postgresql_where="(source_url IS NOT NULL)",
    )
    op.drop_constraint(op.f("uq_raw_job_records_message_id"), "raw_job_records", type_="unique")
    op.create_index(
        "uq_raw_job_records_message_id",
        "raw_job_records",
        ["message_id"],
        unique=True,
        postgresql_where=sa.text("message_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_study_task_progress_user_id"), table_name="study_task_progress")
    op.drop_index(op.f("ix_study_task_progress_user_updated"), table_name="study_task_progress")
    op.drop_index(
        op.f("ix_study_task_question_attempts_user_id"), table_name="study_task_question_attempts"
    )
    op.drop_index(op.f("ix_study_task_snapshots_target_job"), table_name="study_task_snapshots")
    op.drop_index(op.f("ix_study_tasks_user_status_priority_due"), table_name="study_tasks")
    op.create_index(
        "ix_study_tasks_user_status_priority_due",
        "study_tasks",
        [
            "user_id",
            "status",
            "priority",
            "due_date",
            sa.literal_column("created_at DESC"),
            sa.literal_column("id DESC"),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_study_tasks_user_status_priority_due", table_name="study_tasks")
    op.create_index(
        op.f("ix_study_tasks_user_status_priority_due"),
        "study_tasks",
        ["user_id", "status", "priority", "due_date", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_task_snapshots_target_job"),
        "study_task_snapshots",
        ["target_id", "job_post_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_task_question_attempts_user_id"),
        "study_task_question_attempts",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_task_progress_user_updated"),
        "study_task_progress",
        ["user_id", sa.literal_column("updated_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_study_task_progress_user_id"), "study_task_progress", ["user_id"], unique=False
    )
    op.drop_index(
        "uq_raw_job_records_message_id",
        table_name="raw_job_records",
        postgresql_where=sa.text("message_id IS NOT NULL"),
    )
    op.create_unique_constraint(
        op.f("uq_raw_job_records_message_id"),
        "raw_job_records",
        ["message_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f("ix_raw_job_records_source_url"),
        "raw_job_records",
        ["source_id", "source_url"],
        unique=False,
        postgresql_where="(source_url IS NOT NULL)",
    )
    op.create_index(
        op.f("ix_raw_job_records_source_external_job"),
        "raw_job_records",
        ["source_id", "external_job_id"],
        unique=False,
        postgresql_where="(external_job_id IS NOT NULL)",
    )
    op.drop_index(
        "ix_questions_active_type_difficulty_created",
        table_name="questions",
        postgresql_where=sa.text("status = 'active' AND review_status = 'approved'"),
    )
    op.drop_index(
        "ix_questions_active_created_at_id",
        table_name="questions",
        postgresql_where=sa.text("status = 'active' AND review_status = 'approved'"),
    )
    op.create_index(
        op.f("ix_questions_source_review_status"),
        "questions",
        ["source_type", "review_status", "id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_questions_active_type_difficulty_id"),
        "questions",
        ["question_type", "difficulty", "id"],
        unique=False,
        postgresql_where=QUESTIONS_ACTIVE_APPROVED_LEGACY_WHERE,
    )
    op.create_index(
        op.f("ix_question_options_question_correct"),
        "question_options",
        ["question_id", "is_correct"],
        unique=False,
    )
    op.drop_index(
        "ix_question_answers_question_active_source_created",
        table_name="question_answers",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_question_answers_question_status_source"),
        "question_answers",
        ["question_id", "status", "source_type", sa.literal_column("created_at DESC"), "id"],
        unique=False,
    )
    op.drop_index(
        "ix_knowledge_points_active_tree_order",
        table_name="knowledge_points",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_knowledge_points_skill_parent_sort"),
        "knowledge_points",
        ["skill_id", "parent_id", "sort_order", "id"],
        unique=False,
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.drop_index(
        "ix_job_collections_user_folder_active_collected_at",
        table_name="job_collections",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_job_collections_user_folder_active_collected_at"),
        "job_collections",
        ["user_id", "folder_id", sa.literal_column("collected_at DESC")],
        unique=False,
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.drop_index(
        "ix_job_collections_user_active_collected_at",
        table_name="job_collections",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_job_collections_user_active_collected_at"),
        "job_collections",
        ["user_id", sa.literal_column("collected_at DESC")],
        unique=False,
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.drop_index(
        "ix_job_collection_folders_user_active_sort",
        table_name="job_collection_folders",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        op.f("ix_job_collection_folders_user_active_sort"),
        "job_collection_folders",
        ["user_id", "sort_order", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where="((status)::text = 'active'::text)",
    )
    op.drop_constraint(
        "ck_job_collection_folders_status_archived_at", "job_collection_folders", type_="check"
    )
    # ### end Alembic commands ###
