# ruff: noqa: E501
"""add learning preparation tables

Revision ID: cd2ea9cdf292
Revises: c4f5d6e7a8b9
Create Date: 2026-06-16 09:09:02.736955

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cd2ea9cdf292'
down_revision: str | Sequence[str] | None = 'c4f5d6e7a8b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='知识点主键 ID。'),
    sa.Column('skill_id', sa.Integer(), nullable=False, comment='所属标准技能 ID，关联 skills.id。'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父知识点 ID，自关联形成邻接表树结构。'),
    sa.Column('title', sa.String(length=160), nullable=False, comment='知识点标题，同一父节点下不重复。'),
    sa.Column('summary', sa.String(length=500), nullable=True, comment='知识点简短说明。MVP 不保存大段资料正文。'),
    sa.Column('level', sa.Enum('basic', 'intermediate', 'advanced', name='knowledge_point_level', native_enum=False, create_constraint=True, length=30), server_default='basic', nullable=False, comment='知识点难度层级。'),
    sa.Column('depth', sa.Integer(), server_default='0', nullable=False, comment='知识点树深度，根节点为 0。由 service 维护。'),
    sa.Column('sort_order', sa.Integer(), server_default='99', nullable=False, comment='同一父节点下的展示顺序。'),
    sa.Column('status', sa.Enum('active', 'archived', name='knowledge_point_status', native_enum=False, create_constraint=True, length=20), server_default='active', nullable=False, comment='知识点状态。'),
    sa.Column('source_type', sa.Enum('ai', 'official', 'user_supplement', name='content_source_type', native_enum=False, create_constraint=True, length=30), server_default='official', nullable=False, comment='内容来源：ai、official、user_supplement。'),
    sa.Column('source_note', sa.String(length=300), nullable=True, comment='来源补充说明，不保存外部资料正文。'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True, comment='用户补充内容的创建者 ID，官方或 AI 内容可为空。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('depth >= 0', name='ck_knowledge_points_depth_non_negative'),
    sa.CheckConstraint('sort_order >= 0', name='ck_knowledge_points_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'parent_id', 'title', name='uq_knowledge_points_sibling_title'),
    comment='轻量知识点树，用于按技能组织题目和学习任务。'
    )
    op.create_index('ix_knowledge_points_skill_parent_sort', 'knowledge_points', ['skill_id', 'parent_id', 'sort_order', 'id'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_table('questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='题目主键 ID。'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='题目标题，用于列表展示。'),
    sa.Column('question_text', sa.Text(), nullable=False, comment='题干正文。选择题选项不放在这里，放 question_options。'),
    sa.Column('question_hash', sa.String(length=64), nullable=False, comment='题干去重 hash，基于规范化 question_text 生成 sha256，不包含答案和选项。'),
    sa.Column('question_type', sa.Enum('interview_open', 'single_choice', 'multiple_choice', 'true_false', 'short_answer', 'coding', name='question_type', native_enum=False, create_constraint=True, length=30), server_default='interview_open', nullable=False, comment='题目类型：开放面试题、单选、多选、判断、短答、coding。'),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='question_difficulty', native_enum=False, create_constraint=True, length=20), server_default='medium', nullable=False, comment='题目难度。'),
    sa.Column('status', sa.Enum('active', 'archived', name='question_status', native_enum=False, create_constraint=True, length=20), server_default='active', nullable=False, comment='题目状态。'),
    sa.Column('source_type', sa.Enum('ai', 'official', 'user_supplement', name='question_source_type', native_enum=False, create_constraint=True, length=30), server_default='official', nullable=False, comment='题目来源：ai、official、user_supplement。'),
    sa.Column('source_note', sa.String(length=300), nullable=True, comment='来源补充说明，不保存外部平台题目正文来源。'),
    sa.Column('review_status', sa.Enum('draft', 'approved', 'rejected', name='question_review_status', native_enum=False, create_constraint=True, length=20), server_default='approved', nullable=False, comment='审核状态。AI 或用户补充内容后续可先进入 draft。'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True, comment='用户补充题目的创建者 ID。官方或 AI 题目可为空。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_hash', name='uq_questions_question_hash'),
    comment='公共题目表，支持面试开放题、选择题、判断题和后续 coding 题。'
    )
    op.create_index('ix_questions_active_type_difficulty_id', 'questions', ['question_type', 'difficulty', 'id'], unique=False, postgresql_where=sa.text("status = 'active' AND review_status = 'approved'"))
    op.create_index('ix_questions_source_review_status', 'questions', ['source_type', 'review_status', 'id'], unique=False)
    op.create_table('study_tasks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='任务主键 ID。'),
    sa.Column('skill_id', sa.Integer(), nullable=False, comment='任务对应的标准技能 ID。'),
    sa.Column('source', sa.Enum('match_missing_skill', 'match_weak_skill', 'target_skill_summary', 'manual', name='study_task_source', native_enum=False, create_constraint=True, length=40), server_default='manual', nullable=False, comment='任务来源。'),
    sa.Column('source_key', sa.String(length=200), nullable=True, comment='任务生成幂等键，例如 target:12:skill:5:missing，由 service 生成。'),
    sa.Column('task_type', sa.Enum('skill_learning', 'question_practice', 'review', 'project_practice', name='study_task_type', native_enum=False, create_constraint=True, length=30), server_default='question_practice', nullable=False, comment='任务类型。'),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'completed', 'archived', name='study_task_status', native_enum=False, create_constraint=True, length=20), server_default='todo', nullable=False, comment='任务状态。'),
    sa.Column('title', sa.String(length=160), nullable=False, comment='任务标题。'),
    sa.Column('description', sa.String(length=1000), nullable=True, comment='任务说明，保存任务目标和学习建议，不保存大段外部资料。'),
    sa.Column('priority', sa.Integer(), server_default='3', nullable=False, comment='任务优先级，1 最高，5 最低。'),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True, comment='预计耗时，分钟。'),
    sa.Column('actual_minutes', sa.Integer(), nullable=True, comment='实际耗时，分钟。'),
    sa.Column('planned_start_date', sa.Date(), nullable=True, comment='计划开始日期。'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='计划完成日期。'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='任务开始时间。'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='任务完成时间。'),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True, comment='任务归档时间。'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户 ID。所有用户私有数据查询都必须带该字段做隔离。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'todo' AND started_at IS NULL AND completed_at IS NULL AND archived_at IS NULL) OR (status = 'in_progress' AND completed_at IS NULL AND archived_at IS NULL) OR (status = 'completed' AND completed_at IS NOT NULL AND archived_at IS NULL) OR (status = 'archived' AND archived_at IS NOT NULL)", name='ck_study_tasks_status_timestamps'),
    sa.CheckConstraint('actual_minutes IS NULL OR actual_minutes >= 0', name='ck_study_tasks_actual_minutes_non_negative'),
    sa.CheckConstraint('estimated_minutes IS NULL OR estimated_minutes > 0', name='ck_study_tasks_estimated_minutes_positive'),
    sa.CheckConstraint('priority BETWEEN 1 AND 5', name='ck_study_tasks_priority_range'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户学习任务主表，承接目标岗位技能缺口并组织题目清单。'
    )
    op.create_index('ix_study_tasks_user_skill_status', 'study_tasks', ['user_id', 'skill_id', 'status'], unique=False)
    op.create_index('ix_study_tasks_user_status_priority_due', 'study_tasks', ['user_id', 'status', 'priority', 'due_date', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_study_tasks_user_source_key_current', 'study_tasks', ['user_id', 'source_key'], unique=True, postgresql_where=sa.text("source_key IS NOT NULL AND status IN ('todo', 'in_progress')"))
    op.create_table('question_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='答案主键 ID。'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='关联 questions.id。'),
    sa.Column('content', sa.Text(), nullable=False, comment='答案内容，可为面试口述版、详细版或用户补充版。'),
    sa.Column('is_preferred', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='是否为该题当前推荐展示答案。active 状态下同一题最多一个。'),
    sa.Column('source_type', sa.Enum('ai', 'official', 'user_supplement', name='question_answer_source_type', native_enum=False, create_constraint=True, length=30), server_default='official', nullable=False, comment='答案来源：ai、official、user_supplement。'),
    sa.Column('source_note', sa.String(length=300), nullable=True, comment='答案来源补充说明。'),
    sa.Column('status', sa.Enum('active', 'archived', name='question_answer_status', native_enum=False, create_constraint=True, length=20), server_default='active', nullable=False, comment='答案状态。'),
    sa.Column('sort_order', sa.Integer(), server_default='99', nullable=False, comment='答案展示顺序。'),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True, comment='用户补充答案的创建者 ID。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_question_answers_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='题目答案表，支持同一题多个答案版本。'
    )
    op.create_index('ix_question_answers_question_status_sort', 'question_answers', ['question_id', 'status', 'sort_order', 'id'], unique=False)
    op.create_index('uq_question_answers_preferred_active', 'question_answers', ['question_id'], unique=True, postgresql_where=sa.text("is_preferred = true AND status = 'active'"))
    op.create_table('question_options',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='选项主键 ID。'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='关联 questions.id。'),
    sa.Column('option_label', sa.String(length=10), nullable=False, comment='选项标识，例如 A、B、C、D、True、False。'),
    sa.Column('content', sa.Text(), nullable=False, comment='选项内容。'),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='该选项是否为正确答案。单选/判断的正确选项数量由 service 校验。'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='该选项为什么正确或错误的解释，可为空。'),
    sa.Column('sort_order', sa.Integer(), server_default='99', nullable=False, comment='选项展示顺序。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name='ck_question_options_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'option_label', name='uq_question_options_question_label'),
    sa.UniqueConstraint('question_id', 'sort_order', name='uq_question_options_question_sort_order'),
    comment='题目选项表，支持单选、多选、判断题。'
    )
    op.create_index('ix_question_options_question_correct', 'question_options', ['question_id', 'is_correct'], unique=False)
    op.create_table('question_skills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='题目技能关系主键 ID。'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='关联 questions.id。'),
    sa.Column('skill_id', sa.Integer(), nullable=False, comment='关联标准技能 ID。'),
    sa.Column('knowledge_point_id', sa.BigInteger(), nullable=True, comment='关联知识点 ID，可为空。'),
    sa.Column('relation', sa.Enum('primary', 'related', name='question_skill_relation', native_enum=False, create_constraint=True, length=20), server_default='primary', nullable=False, comment='题目和技能的关联角色：primary 主技能，related 相关技能。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'skill_id', 'knowledge_point_id', name='uq_question_skills_question_skill_knowledge'),
    comment='题目与标准技能、知识点的关系表。'
    )
    op.create_index('ix_question_skills_knowledge_point_question', 'question_skills', ['knowledge_point_id', 'question_id'], unique=False)
    op.create_index('ix_question_skills_relation_question', 'question_skills', ['skill_id', 'relation', 'question_id'], unique=False)
    op.create_index('uq_question_skills_primary_question', 'question_skills', ['question_id'], unique=True, postgresql_where=sa.text("relation = 'primary'"))
    op.create_table('study_task_progress',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='进度主键 ID。'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='所属用户 ID。'),
    sa.Column('study_task_id', sa.BigInteger(), nullable=False, comment='关联 study_tasks.id。'),
    sa.Column('total_question_count', sa.Integer(), server_default='0', nullable=False, comment='任务题目总数。'),
    sa.Column('completed_question_count', sa.Integer(), server_default='0', nullable=False, comment='已完成题目数。'),
    sa.Column('practiced_count', sa.Integer(), server_default='0', nullable=False, comment='累计练习次数。'),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False, comment='累计正确次数。'),
    sa.Column('partial_count', sa.Integer(), server_default='0', nullable=False, comment='累计部分正确次数。'),
    sa.Column('incorrect_count', sa.Integer(), server_default='0', nullable=False, comment='累计错误次数。'),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False, comment='累计跳过次数。'),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False, comment='任务进度百分比。'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='任务综合得分，0 到 100，可为空。'),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True, comment='最近练习时间。'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='任务进度完成时间。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_question_count >= 0', name='ck_study_task_progress_completed_non_negative'),
    sa.CheckConstraint('correct_count >= 0 AND partial_count >= 0 AND incorrect_count >= 0 AND skipped_count >= 0', name='ck_study_task_progress_result_counts_non_negative'),
    sa.CheckConstraint('practiced_count >= 0', name='ck_study_task_progress_practiced_non_negative'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_study_task_progress_percent_range'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_study_task_progress_score_range'),
    sa.CheckConstraint('total_question_count >= 0', name='ck_study_task_progress_total_non_negative'),
    sa.ForeignKeyConstraint(['study_task_id'], ['study_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_task_id', name='uq_study_task_progress_task'),
    comment='学习任务整体进度聚合表。'
    )
    op.create_index(op.f('ix_study_task_progress_user_id'), 'study_task_progress', ['user_id'], unique=False)
    op.create_index('ix_study_task_progress_user_updated', 'study_task_progress', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('study_task_questions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='任务题目主键 ID。'),
    sa.Column('study_task_id', sa.BigInteger(), nullable=False, comment='关联 study_tasks.id。'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='关联 questions.id。'),
    sa.Column('status', sa.Enum('pending', 'done', 'skipped', name='study_task_question_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False, comment='任务内题目当前状态。'),
    sa.Column('last_result', sa.Enum('correct', 'partial', 'incorrect', 'skipped', name='study_task_question_result', native_enum=False, create_constraint=True, length=20), nullable=True, comment='最近一次练习结果。'),
    sa.Column('last_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='最近一次练习得分。'),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False, comment='练习次数。'),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True, comment='最近练习时间。'),
    sa.Column('sort_order', sa.Integer(), server_default='99', nullable=False, comment='任务内题目顺序。'),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='题目加入任务时间。'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='题目完成时间。'),
    sa.Column('skipped_at', sa.DateTime(timezone=True), nullable=True, comment='题目跳过时间。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending' AND completed_at IS NULL AND skipped_at IS NULL) OR (status = 'done' AND completed_at IS NOT NULL AND skipped_at IS NULL) OR (status = 'skipped' AND skipped_at IS NOT NULL)", name='ck_study_task_questions_status_timestamps'),
    sa.CheckConstraint('attempt_count >= 0', name='ck_study_task_questions_attempt_count_non_negative'),
    sa.CheckConstraint('last_score IS NULL OR (last_score >= 0 AND last_score <= 100)', name='ck_study_task_questions_last_score_range'),
    sa.CheckConstraint('sort_order >= 0', name='ck_study_task_questions_sort_order_non_negative'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_task_id'], ['study_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_task_id', 'question_id', name='uq_study_task_questions_task_question'),
    comment='学习任务内题目清单，保存当前状态和最近一次练习摘要。'
    )
    op.create_index('ix_study_task_questions_task_status_sort', 'study_task_questions', ['study_task_id', 'status', 'sort_order', 'id'], unique=False)
    op.create_table('study_task_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='快照主键 ID。'),
    sa.Column('study_task_id', sa.BigInteger(), nullable=False, comment='关联 study_tasks.id。'),
    sa.Column('target_id', sa.BigInteger(), nullable=True, comment='生成时的目标岗位 ID 快照。'),
    sa.Column('job_post_id', sa.BigInteger(), nullable=True, comment='生成时的岗位 ID 快照。'),
    sa.Column('skill_name_snapshot', sa.String(length=120), nullable=False, comment='生成时技能名称快照。'),
    sa.Column('job_title_snapshot', sa.String(length=200), nullable=True, comment='生成时岗位标题快照。'),
    sa.Column('company_name_snapshot', sa.String(length=200), nullable=True, comment='生成时公司名称快照。'),
    sa.Column('target_title_snapshot', sa.String(length=200), nullable=True, comment='生成时目标标题快照。'),
    sa.Column('match_status_snapshot', sa.String(length=20), nullable=True, comment='生成时的技能覆盖状态快照，例如 missing、weak。'),
    sa.Column('required_level_snapshot', sa.Integer(), nullable=True, comment='生成时 required_level 快照。'),
    sa.Column('user_level_snapshot', sa.Integer(), nullable=True, comment='生成时用户技能等级快照。'),
    sa.Column('is_primary_target_snapshot', sa.Boolean(), nullable=True, comment='生成时是否主目标快照。'),
    sa.Column('target_priority_snapshot', sa.Integer(), nullable=True, comment='生成时目标优先级快照。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('required_level_snapshot IS NULL OR required_level_snapshot BETWEEN 1 AND 5', name='ck_study_task_snapshots_required_level_range'),
    sa.CheckConstraint('user_level_snapshot IS NULL OR user_level_snapshot BETWEEN 1 AND 5', name='ck_study_task_snapshots_user_level_range'),
    sa.ForeignKeyConstraint(['study_task_id'], ['study_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_task_id', name='uq_study_task_snapshots_task'),
    comment='学习任务生成时的岗位、目标、技能缺口上下文快照。'
    )
    op.create_index('ix_study_task_snapshots_target_job', 'study_task_snapshots', ['target_id', 'job_post_id'], unique=False)
    op.create_table('study_task_question_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='作答记录主键 ID。'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='所属用户 ID。'),
    sa.Column('study_task_id', sa.BigInteger(), nullable=False, comment='关联 study_tasks.id。'),
    sa.Column('study_task_question_id', sa.BigInteger(), nullable=False, comment='关联 study_task_questions.id。'),
    sa.Column('question_id', sa.BigInteger(), nullable=False, comment='关联 questions.id，冗余保存便于查询。'),
    sa.Column('result', sa.Enum('correct', 'partial', 'incorrect', 'skipped', name='study_task_question_attempt_result', native_enum=False, create_constraint=True, length=20), nullable=False, comment='本次作答结果。'),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True, comment='本次作答得分，0 到 100。'),
    sa.Column('selected_option_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='选择题本次选择的 option_id 列表。'),
    sa.Column('answer_text', sa.Text(), nullable=True, comment='开放题、短答题或 coding 题的本次作答内容。'),
    sa.Column('feedback', sa.Text(), nullable=True, comment='本次作答反馈。MVP 可为空，后续可由 AI 生成。'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='本次作答耗时，秒。'),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='作答时间。'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds >= 0', name='ck_study_task_question_attempts_duration_non_negative'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_study_task_question_attempts_score_range'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['study_task_id'], ['study_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['study_task_question_id'], ['study_task_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='学习任务内题目作答流水表，保存每次练习记录。'
    )
    op.create_index('ix_study_task_question_attempts_task_question_attempted', 'study_task_question_attempts', ['study_task_question_id', sa.literal_column('attempted_at DESC')], unique=False)
    op.create_index(op.f('ix_study_task_question_attempts_user_id'), 'study_task_question_attempts', ['user_id'], unique=False)
    op.create_index('ix_study_task_question_attempts_user_task_attempted', 'study_task_question_attempts', ['user_id', 'study_task_id', sa.literal_column('attempted_at DESC')], unique=False)
    op.alter_column('job_collections', 'folder_id',
               existing_type=sa.BIGINT(),
               comment='收藏所属收藏夹 ID。默认情况下指向用户默认收藏夹。',
               existing_comment='收藏所属收藏夹 ID。为空表示默认收藏/未分组。',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_collections', 'folder_id',
               existing_type=sa.BIGINT(),
               comment='收藏所属收藏夹 ID。为空表示默认收藏/未分组。',
               existing_comment='收藏所属收藏夹 ID。默认情况下指向用户默认收藏夹。',
               existing_nullable=True)
    op.drop_index('ix_study_task_question_attempts_user_task_attempted', table_name='study_task_question_attempts')
    op.drop_index(op.f('ix_study_task_question_attempts_user_id'), table_name='study_task_question_attempts')
    op.drop_index('ix_study_task_question_attempts_task_question_attempted', table_name='study_task_question_attempts')
    op.drop_table('study_task_question_attempts')
    op.drop_index('ix_study_task_snapshots_target_job', table_name='study_task_snapshots')
    op.drop_table('study_task_snapshots')
    op.drop_index('ix_study_task_questions_task_status_sort', table_name='study_task_questions')
    op.drop_table('study_task_questions')
    op.drop_index('ix_study_task_progress_user_updated', table_name='study_task_progress')
    op.drop_index(op.f('ix_study_task_progress_user_id'), table_name='study_task_progress')
    op.drop_table('study_task_progress')
    op.drop_index('uq_question_skills_primary_question', table_name='question_skills', postgresql_where=sa.text("relation = 'primary'"))
    op.drop_index('ix_question_skills_relation_question', table_name='question_skills')
    op.drop_index('ix_question_skills_knowledge_point_question', table_name='question_skills')
    op.drop_table('question_skills')
    op.drop_index('ix_question_options_question_correct', table_name='question_options')
    op.drop_table('question_options')
    op.drop_index('uq_question_answers_preferred_active', table_name='question_answers', postgresql_where=sa.text("is_preferred = true AND status = 'active'"))
    op.drop_index('ix_question_answers_question_status_sort', table_name='question_answers')
    op.drop_table('question_answers')
    op.drop_index('uq_study_tasks_user_source_key_current', table_name='study_tasks', postgresql_where=sa.text("source_key IS NOT NULL AND status IN ('todo', 'in_progress')"))
    op.drop_index('ix_study_tasks_user_status_priority_due', table_name='study_tasks')
    op.drop_index('ix_study_tasks_user_skill_status', table_name='study_tasks')
    op.drop_table('study_tasks')
    op.drop_index('ix_questions_source_review_status', table_name='questions')
    op.drop_index('ix_questions_active_type_difficulty_id', table_name='questions', postgresql_where=sa.text("status = 'active' AND review_status = 'approved'"))
    op.drop_table('questions')
    op.drop_index('ix_knowledge_points_skill_parent_sort', table_name='knowledge_points', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('knowledge_points')
    # ### end Alembic commands ###
