# ruff: noqa: E501
"""refactor auth/user/job/skill tables

Revision ID: d757db30fc0e
Revises:
Create Date: 2026-06-10 18:17:58.715553

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d757db30fc0e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_sources",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="岗位来源主键 ID。"
        ),
        sa.Column(
            "platform",
            sa.String(length=50),
            nullable=False,
            comment="来源平台标识，例如 alibaba、tencent、jaabz；同平台可有多个来源实例。",
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="来源展示名称，例如 阿里社招、阿里校招、腾讯招聘、Jaabz。",
        ),
        sa.Column(
            "base_url",
            sa.String(length=500),
            nullable=False,
            comment="来源实例基础 URL，例如社招入口、校招入口或第三方职位列表页。",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="该来源是否启用。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "base_url", name="uq_job_sources_platform_base_url"),
        comment="岗位来源表，同一平台可按不同 base_url 拆分具体来源。",
    )
    op.create_table(
        "skills",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="标准技能主键 ID。"
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="标准技能展示名称，例如 Python、FastAPI、PostgreSQL。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_skills_name"),
        comment="标准技能字典表，被岗位、用户技能、八股题等模块复用。",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="用户主键 ID。"),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "disabled",
                "deleted",
                name="user_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="active",
            nullable=False,
            comment="用户账号状态：active 可用，disabled 禁用，deleted 逻辑删除。",
        ),
        sa.Column(
            "is_superuser",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="是否为平台超级管理员，用于后台管理和越权保护场景。",
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="用户最近一次成功登录时间，用于安全审计和活跃度统计。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="平台用户主体表，只保存用户状态、权限标记和生命周期信息。",
    )
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_table(
        "auth_identities",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="登录身份主键 ID。"
        ),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="所属用户 ID，关联 users.id。"),
        sa.Column(
            "provider",
            sa.Enum(
                "email",
                "phone",
                "github",
                "google",
                name="auth_provider",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
            comment="登录身份提供方，例如 email、phone、github、google。",
        ),
        sa.Column(
            "provider_subject",
            sa.String(length=255),
            nullable=False,
            comment="提供方内的唯一账号标识，例如标准化邮箱、手机号或 OAuth subject。",
        ),
        sa.Column(
            "provider_email",
            sa.String(length=255),
            nullable=True,
            comment="提供方返回或用户绑定的邮箱地址。",
        ),
        sa.Column(
            "provider_phone",
            sa.String(length=32),
            nullable=True,
            comment="提供方返回或用户绑定的手机号。",
        ),
        sa.Column(
            "provider_username",
            sa.String(length=100),
            nullable=True,
            comment="提供方返回的用户名或昵称快照。",
        ),
        sa.Column(
            "provider_avatar_url",
            sa.String(length=500),
            nullable=True,
            comment="提供方返回的头像 URL 快照。",
        ),
        sa.Column(
            "identity_verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="该登录身份被系统确认有效的时间。",
        ),
        sa.Column(
            "provider_email_verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="邮箱被提供方或本系统确认可信的时间。",
        ),
        sa.Column(
            "provider_phone_verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="手机号被提供方或本系统确认可信的时间。",
        ),
        sa.Column(
            "linked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="该登录身份绑定到用户的时间。",
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="该登录身份最近一次成功登录时间。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_subject", name="uq_auth_identities_provider_subject"
        ),
        sa.UniqueConstraint("user_id", "provider", name="uq_auth_identities_user_provider"),
        comment="用户登录身份表，保存邮箱、手机号、第三方账号等可登录身份。",
    )
    op.create_table(
        "raw_job_records",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="原始岗位记录主键 ID。",
        ),
        sa.Column(
            "source_id", sa.Integer(), nullable=False, comment="来源 ID，关联 job_sources.id。"
        ),
        sa.Column(
            "message_id",
            sa.String(length=64),
            nullable=True,
            comment="消息唯一 ID。RabbitMQ 模式下用于幂等；文件导入可为空。",
        ),
        sa.Column(
            "trace_id",
            sa.String(length=64),
            nullable=True,
            comment="链路追踪 ID，用于串联 crawler、MQ、ingestion worker 日志。",
        ),
        sa.Column(
            "producer",
            sa.String(length=100),
            nullable=True,
            comment="生产者名称，例如 alibaba-crawler、excel-importer。",
        ),
        sa.Column(
            "external_job_id",
            sa.String(length=120),
            nullable=True,
            comment="来源平台自己的岗位 ID。只放 raw 表，不放 job_posts 主表。",
        ),
        sa.Column(
            "source_url",
            sa.String(length=1000),
            nullable=True,
            comment="来源岗位详情 URL。规范化详情表可冗余一份用于展示。",
        ),
        sa.Column(
            "raw_content_hash",
            sa.String(length=64),
            nullable=False,
            comment="raw_payload 规范化序列化后的内容 hash，用于幂等和变化检测。",
        ),
        sa.Column(
            "skill_content_hash",
            sa.String(length=64),
            nullable=True,
            comment="raw_payload 中结构化技能候选内容的 hash，用于追踪技能字段变化。",
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="来源原始字段，PostgreSQL JSONB。",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "normalized",
                "failed",
                "skipped",
                name="raw_job_record_status",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="received",
            nullable=False,
            comment="原始记录处理状态。",
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
            comment="adapter/normalizer 失败时记录错误原因。",
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="爬虫采集到该原始记录的时间，文件导入可为空。",
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="后端收到该原始记录的时间。",
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="后端完成规范化处理的时间。",
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="系统第一次看到该来源记录的时间。",
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="系统最近一次看到该来源记录的时间。",
        ),
        sa.Column(
            "seen_count",
            sa.Integer(),
            server_default="1",
            nullable=False,
            comment="同一来源 raw 内容被重复看到的次数。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["source_id"], ["job_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id", name="uq_raw_job_records_message_id"),
        sa.UniqueConstraint("source_id", "raw_content_hash", name="uq_raw_job_records_source_hash"),
        comment="原始岗位记录表，保存爬虫或文件导入推来的 raw payload。",
    )
    op.create_index(
        op.f("ix_raw_job_records_skill_content_hash"),
        "raw_job_records",
        ["skill_content_hash"],
        unique=False,
    )
    op.create_index(
        "ix_raw_job_records_source_external_job",
        "raw_job_records",
        ["source_id", "external_job_id"],
        unique=False,
        postgresql_where=sa.text("external_job_id IS NOT NULL"),
    )
    op.create_index(
        "ix_raw_job_records_source_url",
        "raw_job_records",
        ["source_id", "source_url"],
        unique=False,
        postgresql_where=sa.text("source_url IS NOT NULL"),
    )
    op.create_table(
        "skill_aliases",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="技能别名主键 ID。"
        ),
        sa.Column("skill_id", sa.Integer(), nullable=False, comment="关联标准技能 ID。"),
        sa.Column(
            "alias",
            sa.String(length=100),
            nullable=False,
            comment="别名归一化结果。一个 alias 只允许指向一个标准技能。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias", name="uq_skill_aliases_alias"),
        comment="技能别名表，负责把来源 raw skill 归一到标准 skills。",
    )
    op.create_index("ix_skill_aliases_skill_id", "skill_aliases", ["skill_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
            comment="关联 users.id，同时作为用户资料表主键。",
        ),
        sa.Column(
            "display_name",
            sa.String(length=80),
            nullable=False,
            comment="页面展示昵称，可以重复，不用于登录认证。",
        ),
        sa.Column("avatar_url", sa.String(length=500), nullable=True, comment="用户头像 URL。"),
        sa.Column(
            "bio",
            sa.String(length=300),
            nullable=True,
            comment="用户个人简介，控制长度以便直接用于列表和个人页展示。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
        comment="用户公开资料表，与登录身份和密码凭证分离。",
    )
    op.create_table(
        "auth_password_credentials",
        sa.Column(
            "identity_id",
            sa.Integer(),
            nullable=False,
            comment="关联 auth_identities.id，同时作为密码凭证主键。",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="密码哈希值，不保存明文密码。",
        ),
        sa.Column(
            "password_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="密码最近一次更新时间，用于密码轮换和安全审计。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["identity_id"], ["auth_identities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("identity_id"),
        comment="密码凭证表，只保存需要密码登录的身份对应的密码哈希。",
    )
    op.create_table(
        "job_posts",
        sa.Column(
            "id", sa.BigInteger(), autoincrement=True, nullable=False, comment="岗位主键 ID。"
        ),
        sa.Column(
            "source_id", sa.Integer(), nullable=False, comment="来源 ID，关联 job_sources.id。"
        ),
        sa.Column(
            "raw_record_id",
            sa.BigInteger(),
            nullable=True,
            comment="最近一次生成或更新该规范化岗位的原始记录 ID。",
        ),
        sa.Column(
            "fingerprint",
            sa.String(length=64),
            nullable=False,
            comment="规范化岗位去重指纹。数据库唯一约束兜底防重。",
        ),
        sa.Column(
            "title",
            sa.String(length=300),
            nullable=False,
            comment="岗位标题，用于列表展示。MVP 使用 ILIKE，后续可接 ES/embedding。",
        ),
        sa.Column(
            "company_name",
            sa.String(length=200),
            nullable=True,
            comment="公司名称。MVP 不单独拆 companies 表。",
        ),
        sa.Column(
            "locations",
            sa.String(length=500),
            nullable=True,
            comment="岗位地点文本，多个地点用 / 拼接。MVP 不拆国家、城市、区域表。",
        ),
        sa.Column(
            "is_remote",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="是否远程岗位。只保留这个可稳定筛选的地点结构化字段。",
        ),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "contract",
                "internship",
                "temporary",
                "freelance",
                "unknown",
                name="employment_type",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="unknown",
            nullable=False,
            comment="雇佣类型，例如 full_time、part_time、contract、internship。",
        ),
        sa.Column(
            "workplace_type",
            sa.Enum(
                "onsite",
                "hybrid",
                "remote",
                "unknown",
                name="workplace_type",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="unknown",
            nullable=False,
            comment="办公方式，例如 onsite、hybrid、remote。",
        ),
        sa.Column(
            "experience_level",
            sa.Enum(
                "intern",
                "entry",
                "junior",
                "mid",
                "senior",
                "lead",
                "director",
                "not_applicable",
                "unknown",
                name="experience_level",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="unknown",
            nullable=False,
            comment="经验等级。",
        ),
        sa.Column(
            "experience_min_years",
            sa.Integer(),
            nullable=True,
            comment="最低经验年限，无法解析则为空。",
        ),
        sa.Column(
            "experience_max_years",
            sa.Integer(),
            nullable=True,
            comment="最高经验年限，无法解析则为空。",
        ),
        sa.Column(
            "education_level",
            sa.Enum(
                "none",
                "associate",
                "bachelor",
                "master",
                "doctor",
                "unknown",
                name="education_level",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            server_default="unknown",
            nullable=False,
            comment="学历等级。",
        ),
        sa.Column(
            "salary_text",
            sa.String(length=120),
            nullable=True,
            comment="原始薪资文本，例如 10-15K、150-200/天、100-150K/year。",
        ),
        sa.Column(
            "salary_min",
            sa.Integer(),
            nullable=True,
            comment="解析后的最低薪资数值。周期只作为展示字段，不作为当前筛选字段。",
        ),
        sa.Column(
            "salary_max",
            sa.Integer(),
            nullable=True,
            comment="解析后的最高薪资数值。周期只作为展示字段，不作为当前筛选字段。",
        ),
        sa.Column(
            "salary_currency",
            sa.String(length=10),
            server_default="CNY",
            nullable=False,
            comment="薪资币种，默认 CNY。",
        ),
        sa.Column(
            "salary_period",
            sa.Enum(
                "hour",
                "day",
                "month",
                "year",
                "unknown",
                name="salary_period",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="unknown",
            nullable=False,
            comment="薪资周期，例如 hour、day、month、year；无法判断为 unknown。",
        ),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="来源平台发布时间，无法解析则为空。",
        ),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="系统第一次发现该岗位的时间。",
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="系统最近一次看到该岗位的时间。",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "closed",
                "expired",
                "unknown",
                name="job_post_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="open",
            nullable=False,
            comment="规范化岗位状态。",
        ),
        sa.Column(
            "skill_content_hash",
            sa.String(length=64),
            nullable=True,
            comment="当前已同步到 job_post_skills 的结构化技能内容 hash。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["raw_record_id"], ["raw_job_records.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_id"], ["job_sources.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_job_posts_fingerprint"),
        comment="规范化岗位热数据表，用于列表、筛选、排序和状态判断。",
    )
    op.create_index(op.f("ix_job_posts_deleted_at"), "job_posts", ["deleted_at"], unique=False)
    op.create_index(
        "ix_job_posts_open_created_at_id",
        "job_posts",
        [sa.literal_column("created_at DESC"), sa.literal_column("id DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_job_posts_open_published_at_asc_id",
        "job_posts",
        [sa.literal_column("published_at ASC NULLS LAST"), sa.literal_column("id ASC")],
        unique=False,
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.create_index(
        "ix_job_posts_open_published_at_id",
        "job_posts",
        [sa.literal_column("published_at DESC NULLS LAST"), sa.literal_column("id DESC")],
        unique=False,
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.create_index(
        op.f("ix_job_posts_raw_record_id"), "job_posts", ["raw_record_id"], unique=False
    )
    op.create_index(op.f("ix_job_posts_source_id"), "job_posts", ["source_id"], unique=False)
    op.create_table(
        "job_post_details",
        sa.Column(
            "job_post_id",
            sa.BigInteger(),
            nullable=False,
            comment="关联 job_posts.id，同时作为详情表主键。",
        ),
        sa.Column(
            "source_url",
            sa.String(length=1000),
            nullable=True,
            comment="来源岗位详情 URL。external_job_id 不放这里，放 raw_job_records。",
        ),
        sa.Column(
            "company_url",
            sa.String(length=1000),
            nullable=True,
            comment="来源平台上的公司 URL，可为空。",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="岗位正文。MVP 合并职责、要求、详情等文本，不单独拆 requirements。",
        ),
        sa.Column(
            "has_visa_sponsorship",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="是否明确提供签证支持。冷字段，不参与高频查询。",
        ),
        sa.Column(
            "has_relocation_support",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="是否明确提供搬迁支持。冷字段，不参与高频查询。",
        ),
        sa.Column(
            "work_authorization_note",
            sa.String(length=500),
            nullable=True,
            comment="工作许可、签证、搬迁相关的原始说明或清洗后的备注。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_post_id"], ["job_posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("job_post_id"),
        comment="岗位详情冷数据表，保存正文、来源 URL、公司 URL、签证/搬迁等低频字段。",
    )
    op.create_table(
        "job_post_skills",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
            comment="岗位技能关系主键 ID。",
        ),
        sa.Column("job_post_id", sa.BigInteger(), nullable=False, comment="关联 job_posts.id。"),
        sa.Column("skill_id", sa.Integer(), nullable=False, comment="关联标准 skills.id。"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["job_post_id"], ["job_posts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_post_id", "skill_id", name="uq_job_post_skills_job_skill"),
        comment="岗位技能关系表，只记录岗位与清洗后标准技能的事实关系。",
    )
    op.create_index(
        "ix_job_post_skills_skill_job", "job_post_skills", ["skill_id", "job_post_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_post_skills_skill_job", table_name="job_post_skills")
    op.drop_table("job_post_skills")
    op.drop_table("job_post_details")
    op.drop_index(op.f("ix_job_posts_source_id"), table_name="job_posts")
    op.drop_index(op.f("ix_job_posts_raw_record_id"), table_name="job_posts")
    op.drop_index(
        "ix_job_posts_open_published_at_id",
        table_name="job_posts",
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_job_posts_open_published_at_asc_id",
        table_name="job_posts",
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.drop_index(
        "ix_job_posts_open_created_at_id",
        table_name="job_posts",
        postgresql_where=sa.text("status = 'open' AND deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_job_posts_deleted_at"), table_name="job_posts")
    op.drop_table("job_posts")
    op.drop_table("auth_password_credentials")
    op.drop_table("user_profiles")
    op.drop_index("ix_skill_aliases_skill_id", table_name="skill_aliases")
    op.drop_table("skill_aliases")
    op.drop_index(
        "ix_raw_job_records_source_url",
        table_name="raw_job_records",
        postgresql_where=sa.text("source_url IS NOT NULL"),
    )
    op.drop_index(
        "ix_raw_job_records_source_external_job",
        table_name="raw_job_records",
        postgresql_where=sa.text("external_job_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_raw_job_records_skill_content_hash"), table_name="raw_job_records")
    op.drop_table("raw_job_records")
    op.drop_table("auth_identities")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_table("users")
    op.drop_table("skills")
    op.drop_table("job_sources")
    # ### end Alembic commands ###
